name: happyouth
favicon: null
layout_spectrum: 0.43318
typography_spectrum: 0.1210262596141547
title: The Happy - Healthy life is our Youth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#83b742'
    - '#29272b'
    - '#b0694a'
    - '#e8a7c9'
  brandStrength: 0.4808624323923141
  lightness: 0.6098049427382648
  saturation: 0.05052006314508617
  rhythmicContrast: 0.07698802649974823
purpose: []
